# Generated by Django 5.1.1 on 2024-09-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('country_of_birth', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
    ]
